# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c57b1ea61a241c829954e4619622a8659f011fd313a3ec4fe176b05935b1012291e891e9f313ac74f69560bb482470cf9228e15b98434ce264d3d765f4f3cd1

test:
  secret_key_base: 0f38d213b999e38f95bf0a5bf65cf979b410468acf96d764f6681bb399c96a9c6692cde662f986d05e4b7de3fa19e21fe10196e4f4d1922b0450d552a10d0041

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
